### ISSUE TITLE
#Task 1.1.2: Related Background Literature

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#11]

**Comment by Kohgi88** [comment]
Task title ID:#1.1.2

What is the task about? Please describe in detail.
Include research you have done about the domain that your project is in here. Also, any materials you read to help you with the project, and any competing methods/APIs/software.

What are the goals of the task? Please describe in detail.
The goal is to leverage research and existing resources to inform the project's approach, enhance its quality, and ensure it addresses real-world needs effectively. This approach helps in delivering a successful and competitive project within the chosen domain.

Success or completion criteria. Please describe in detail.
NA

Allocated time
1 day

Start date and end date of the issue/task
04/09/23 - 05/09/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@Kohgi88

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
Medium

Describe the work done in detail.
The security industry in Singapore is on a steady growth trajectory, driven by increasing concerns about security. This heightened concern has translated into an increase of demand for professional security guard services across a wide spectrum of sectors, including residential complexes, commercial properties, government institutions, transportation hubs, and critical infrastructure facilities. (Ministry of Home Affairs Singapore, n.d.)

Technological advancements have paved the way for the integration of security guard management software, which has become important in enhancing the operational efficiency and effectiveness of security services. This software offers various indispensable features, including streamlined scheduling and rostering, simplifying compliance with regulations and training requirements (GuardsPro, n.d.). By helping with precise scheduling, preventing staffing imbalances, and optimizing resource utilisation, it contributes to cost savings while also making time-consuming administrative tasks easier.

Despite the numerous advantages, there are also drawbacks to consider. Getting and implementing security guard management software involves upfront costs, which include software licenses, hardware, and staff training (Foote, 2022). Also, given that a huge portion of security guards in Singapore are part of the aging population (See, 2013), there might be a learning curve as staff and supervisors adapt to these new systems, potentially leading to a decrease in work efficiency. Resistance to change among employees, inadequate training, and complexity in software usage are also challenges that hinder the full potential of this technology (sciencedaily, 2018).

In our study, we found some existing solutions made by other companies. MobiGuard by Sovereign Security Services is a mobile app-based solution centralizing guard duties and enhancing efficiency with features like real-time patrol data capture and GPS tracking (Sovereign Security Services Pte Ltd, n.d.). GuardsPro, a feature-rich SaaS platform, offers capabilities such as location tracking, guard attendance, online reporting, idle alerts, visitor management, and payroll integration (GuardsPro, n.d.). 

Some off-the-shelf solutions may offer limited customisation options, making it challenging to tailor the software to specific scheduling needs (Roomi, 2021). For example, having too many features that might not be needed may add unnecessary costs, or missing important features would not solve, in this case, workload management problems. Therefore, we believe that creating a software that is tailor made for our client would be the most cost effective solution.


Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
Start date: 04/09/23
End date: 05/09/23
