### ISSUE TITLE
#Task 1.1.3: Intended Audience and Document Overview

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#12]

**Comment by Kohgi88** [comment]
Task title ID: #1.1.3

What is the task about? Please describe in detail.
Describe the different types of reader that the document is intended for, such as developers, project managers, marketing staff, users, testers, and documentation writers (In your case it would probably be the “client” and the professor). Describe what the rest of this document contains and how it is organized. Suggest a sequence for reading the document, beginning with the overview sections and proceeding through the sections that are most pertinent to each reader type.

What are the goals of the task? Please describe in detail.
The goals of the task are to create a comprehensive document that effectively communicates information about a software project within a security company to various types of readers or stakeholders. 

Success or completion criteria. Please describe in detail.
NA

Allocated time
1 day

Start date and end date of the issue/task
05/09/23 - 06/09/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@Kohgi88 

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
High

Describe the work done in detail.
This document is intended for the security company’s management team, security officers, developers, and support staff. 

Management Team (client): The management team needs to know the project’s goals, its scope, and how the proposed system would benefit the company’s workforce management. High-level project details and outcomes would be of the utmost interest to them. 

Security Officers: Security Officers will use the software on a frequent basis. They must understand how the system can influence their work, manage their workload, and improve their work ethic. 

Developers: Developers are responsible for building the software. They need detailed technical knowledge, such as system architecture, coding stacks, and technology stack that was selected. 

Support Staff: Support Staff should be available to assist end-users (security officers) with any inquiries or problems relating to the software. They ought to be familiar with the system functions and typical user queries. 

This document contains an overall description of the software, including requirements, functionalities, requirements, use cases, and project estimation and planning for the project. It provides a comprehensive overview of the proposed web-based workload management system for the security company and is organized into distinct sections, beginning with an introduction that outlines the document's purpose. The overall project description, specific requirements, project estimation, and planning are then covered. Use case descriptions and a data dictionary are also included in the appendices as additional details. 

The following sequence is recommended for the document to focus on the needs and interests of the following reader types.

For Management Team
To read the “Introduction” (Section 1) to understand the project’s objectives,scope, and strategic implications. To read the “Overall Description” (Section 2) for a detailed overview of the project, with an emphasis on the potential impacts on workforce management. To read the “Project Estimation and Plan” (Section 4) to understand the project’s timeline, resource location, and expected outcomes. The Management Team may also want to read the entire project document to fully comprehend the project and consult with the project team regarding any queries and concerns. 

For Security Officers
To read the “Introduction” (Section 1) carefully to gain a better understanding of how the project will affect your work duties and work life management. To read the “Overall Description” (Section 2) to fully understand how the system will impact your work procedures and job efficiency. To read the “Specific Requirements'' (Section 3) to learn about specific functions that can help in the usage of the system. 

For Developers
To read the “Specific Requirements” (Section 3) to get a thorough technical understanding of the system requirements. This section will provide developers with information on system architecture, coding stacks, and technology stack choices by paying close attention to interactions within the components in the system. To read “Project Estimation and Plan” (Section 4) to analyze technical tasks, development timelines, and resource allocation. 

For Support Staff
To read “Introduction” (Section 1) and “Overall Description” (Section 2) to effectively assist users and address common user queries. These sections provide an overview of the system's purpose and functionality. To read “Appendix A” (Use Case Descriptions) to learn about specific scenarios in which users may interact with the system to resolve user issues. To read “Appendix B” (Data Dictionary) to learn about specific scenarios in which users can interact with the system to help understand the meaning of different terms and data fields that users may ask. 

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
Start date: 05/09/23
End date: 06/09/23
