### ISSUE TITLE
#Task 1.1.4: References and Acknowledgments

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#13]
Issue Description: Incorporating External References into Documentation

Task Title ID: 1.1.4

Task Description: The task involves integrating external references into our documentation, acknowledging and referencing information and insights gained from external resources from renowned security management websites. 

Task Goals: The goal of the task is to properly acknowledge and reference external resources that have contributed information and valuable insights to our documentation. This ensures transparency and compliance with citation standards.

Success and Completion Criteria Description: The task will be considered successful when all external references, including web addresses and description of insights gained from security management websites, have been accurately incorporated into our documentation. 

Allocated Time: 2 days

Start Date & End Date of the Task: 05/09/2023-06/09/2023 

Owner of the task: Angie 

Status of task: To-Do

Priority of Task: Medium

**Comment by user963087** [comment]
Work done Description: The work involved reviewing and summarizing insights obtained from external sources, namely GuardsPro and Sovereign Security Services. These insights and information can be applied and considered into our security management systems and related solutions. 

Work committed to repo: Not Applicable for this task

Impact on completion deadline: The work contributes positively to the completion of the documentation by ensuring that all external references are properly cited and integrated. It does not overall completion deadline significantly as we can always review to update and improve on our web application. 

Changes to success or completion criteria of task: No changes to success or completion criteria. 

Start date and End date of Work done: 05/09/2023-07/09/2023 (3 days)
