### ISSUE TITLE
#Task 1.1.4: Product Overview

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#14]
**Task title ID: #1.1.4**
**What is the task about? Please describe in detail.**
Describe the context and origin of the product being specified

**What are the goals of the task? Please describe in detail.**
The goals of the task is to 

**Success or completion criteria. Please describe in detail.**
1. Paragraph describing product perspective
2. System's Architecture diagram

**Allocated time**
5 days

**Start date and end date of the issue/task**
Start date: 7 sept 2023
End date: 12 sept 2023

**Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.**
Vivian

**Comment by viviannzh** [comment]
**Work done in detail.**
Provided a short paragraph describing product perspective and provided System's Architecture Diagram.

**Has this work been committed to the repo?**
NA

**How does the work affect the completion deadline.**
A well-documented product overview can provide a baseline against which proposed changes can be evaluated. 

**Changes to the success or completion criteria of the task?**
No changes

**Start date and end date of the work done for this comment.**
Start date: 7 sept 2023
End date: 12 sept 2023
