### ISSUE TITLE
#Task 1.1.6: Assumptions and Dependencies

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#15]
**What is the task about? Please describe in detail:** 
The "Assumptions and Dependencies" task is a critical component of the project planning phase. Its purpose is to identify, document, and manage potential risks and external factors that may impact the project's success. This task involves systematically documenting assumptions made about project conditions and identifying dependencies on external factors, processes, or entities.

**What are the goals of the task? Please describe in detail:**
Risk Identification: The primary goal of this task is to identify potential risks and uncertainties that could affect the project's timeline, budget, scope, or quality. By documenting assumptions and dependencies, the project team aims to uncover potential areas of vulnerability.

Risk Mitigation: Another goal is to develop strategies for mitigating identified risks. This includes assessing the impact of incorrect assumptions and planning for contingencies in case dependencies are delayed or disrupted.

Effective Communication: Clear and transparent communication is a crucial goal. The task ensures that all stakeholders, including team members, sponsors, clients, and relevant external parties, have a shared understanding of the factors that might influence the project's outcomes.

Resource Allocation: Documenting dependencies helps in efficient resource allocation and scheduling. This goal is to ensure that the project team can allocate resources optimally based on the availability of dependencies.

Contingency Planning: The task supports the development of contingency plans. When critical dependencies are at risk or when assumptions prove incorrect, the team can activate contingency plans to maintain project progress.

**Success or completion criteria. Please describe in detail.:**
Comprehensive Documentation: Successful completion of this task involves the creation of a comprehensive document that lists all identified assumptions and dependencies, along with relevant details such as their potential impact and mitigation strategies.

Risk Mitigation Strategies: The task is considered successful if it results in the formulation of effective risk mitigation strategies for identified assumptions and dependencies. These strategies should address potential challenges and minimize their impact.

Clear Communication: Success is achieved when all project stakeholders have been informed and are aware of the documented assumptions and dependencies. This ensures that everyone is on the same page regarding potential project risks.

Resource Allocation Plans: Successful completion includes resource allocation plans that account for dependencies. These plans should ensure that resources are used efficiently and that potential resource shortages are anticipated.

Contingency Plans: The presence of well-defined contingency plans for key dependencies and assumptions is a success criterion. These plans should be actionable and designed to minimize project disruptions.

Regular Updates: Success also involves a commitment to regularly review and update the assumptions and dependencies documentation throughout the project's lifecycle. Changes in these factors should be tracked and managed effectively.

**Allocated time**

**Start date and end date of the issue/task**

**Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.**

**The status of the task. This is usually "To-Do" initially.**:
IN-PROGRESS

**What is the Priority of the task?**:
MEDIUM

**Comment by faithlimzx** [comment]
**Describe the work done in detail.**
Assumptions:

Part-Time Staff: Part-time staff can reject one shift assignment.

Security Certificates: Security staff must have valid security certificates.

Fixed Shifts: Shifts are 12 hours long, from 7 am to 7 pm or 7 pm to 7 am, with a one-hour unpaid break.

No Consecutive Shifts: Employees cannot work consecutive shifts in a week.

Availability Accuracy: Staff are expected to provide accurate and up-to-date availability.

Browser Compatibility: The system works best with modern web browsers.

User-Friendly: The system is designed to be user-friendly.

Dependencies:

Database System: The project relies on a specific database system for storing data, and any issues with it could impact the project.

Web Development Framework: The choice of a compatible web development framework is crucial for project success.

User Engagement: Active participation from security guards and managers is essential for the system to function as intended.

API Integration: The project utilizes APIs for authentication, notifications, and reporting, which need proper integration and support.

Terminology Alignment: The project uses industry-standard terms to ensure clear and consistent documentation.


**Has this work been committed to the repo?**
Yes

**How does the work affect the completion deadline.**
Some updates needed.

**Are there any changes to the success or completion criteria of the task? If yes, please describe the details.**
No
**Start date and end date of the work done for this comment.**
12/09/2023 - 16/09/2023

**Comment by faithlimzx** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/78584557/f2291ec8-1bb1-4ffc-9aa4-806780de48ab)
