### ISSUE TITLE
#Task 1.3.2: Detailed Use Case Description (UC-5 to UC-7)

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#17]
Task title ID: https://github.com/hxijxe/ict-inf2001-p3-6/issues/12

What is the task about? Please describe in detail.
The task involves creating detailed use case descriptions for Use Cases 5, 6 and 7, which are "Manage Shift", "Manage Shift Location" and "Manage Shift Preference" respectively.

What are the goals of the task? Please describe in detail.
The primary goals of this task are to create clear, well-structured use case descriptions for Use Cases 5, 6 and 7, ensuring alignment with project objectives, comprehensiveness, accuracy, and documentation quality. These descriptions will serve as valuable references for project stakeholders and developers, enhancing the management of work shifts and their corresponding locations within the system.

Success or completion criteria. Please describe in detail.
Completion of use case descriptions

Allocated time
7 Days

Start date and end date of the issue/task
13/09/23 - 19/09/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@avintech

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
Medium

**Comment by avintech** [comment]
Describe the work done in detail.
In Use Case 5, titled "Manage Shift," a manager, when logged into the security management system, can perform shift management tasks like creating, updating, and deleting shifts. The successful execution of these tasks involves input validation and confirmation. In Use Case 6, titled "Manage Shift Location," a manager with system access can create, update, or delete shift locations, primarily when new sites need to be served. Similar to Use Case 5, this use case involves input validation, confirmation, and modification of location details when needed. Both use cases follow a structured process within the security management system, ensuring the accurate management of shifts and their associated locations by the manager. Use Case 7 involves creating, updating and deleting shift preferences. The successful execution of these tasks involves input validation and confirmation.

Has this work been committed to the repo?
No

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
Start date: 13/09/23
End date: 19/09/23

**Comment by avintech** [comment]
Use Case ID: UC-5

Use Case Name: Manage Shift

Description: This use case outlines the process by which a manager can manage shifts within the security management system. The manager can create, update, and delete shifts as part of their responsibilities.

Primary Actor: Manager

Preconditions:

Manager must be logged into the system.
Creating shift: Would be when a new shift is needed.
Updating shift: Would be when there are changes to the shift.
Deleting shift: Would be when the shift is no longer needed.
Postconditions: Manager has successfully created, updated, or deleted shifts as needed.

Main Success Scenarios:

1. User Logs into System.
2. System determines the user role and displays the corresponding landing page.
3. Manager selects ‘Manage Shift’ in the system.
4. System shows a list of existing shifts in the database.
5. Manager selects ‘Create Shift’ from the page.
6. System shows create shift form.
7. System performs UC-4 (Filter Shift).
8. In the event that multiple security personnel request the same shift allocation, the system displays the requests in a queue in the order they were received.
9. Manager fills in valid new shift information.
10. Manager submits the form.
11. System validates input.
12. System creates the new shift.

Alternative Scenarios:
5a. Manager Update Shift

5a1. Manager selects ‘Update Shift’ on the selected shift.
5a2. System shows existing shift information in a form.
5a3. Manager fills in valid new shift information in the form.
5a4. Manager submits the form.
5a5. System validates input.
5a6. System updates the existing shift.

5b. Manager Delete Shift

5b1. Manager selects ‘Delete Shift’ on the selected shift.
5b2. System prompts confirmation for shift deletion.
5b3. Manager confirms deletion.
5b4. System deletes the selected shift.

11a. Conflicts or errors in the information provided by the Manager (e.g., duplicate shift information)

11a1. The system displays an error message and prompts the Manager to correct the information.
11a2. Repeat from Step 9.

**Comment by avintech** [comment]
Use Case ID: UC-6

Use Case Name: Manage Shift Location

Description: This use case outlines the process by which a manager can manage shift locations within the security management system. The manager can create, update, and delete shift locations as part of their responsibilities. This could happen when there is a new site for the security company to serve.

Primary Actor: Manager

Preconditions:

Manager must be logged into the system.
When there is a need to create/update/delete a location.
Postconditions: Manager has successfully created, updated, or deleted shift location as needed.

Main Success Scenarios:

1. User Logs into system.
2. System validates login information, determines user roles and displays the corresponding landing page.
3. Manager selects ‘Manage Locations’ in the system.
4. System shows a list of existing locations in the database.
5. Manager selects ‘Create Location’.
6. System shows a create location form.
7. Manager fills in valid new location information in the form.
8. Manager submits the form.
9. System validates input.
10. System creates the new location.

Alternative Scenarios:

5a. Update Shift Location:

5a1. Manager selects ‘Update Location’ on selected location.
5a2. System shows current location details for editing in a form.
5a3. Manager makes modifications to the existing location.
5a4. Manager clicks on ‘Confirm’ to confirm the update and submit the form.
5a5. System validates input.
5a6. System updates the selected location.

5b. Delete Shift Location:

5b1. Manager selects ‘Delete Location’ on selected location.
5b2. System prompts manager to confirm the deletion.
5b3. Manager clicks on ‘Confirm’ to confirm the deletion.
5b4. System deletes the location.

9a. Conflicts or errors in the information provided by the Manager (e.g., duplicate shift information):

9a1. The system displays an error message and prompts the Manager to correct the information.
9a2. Repeat from Step 7.

**Comment by avintech** [comment]
Use Case ID: UC-7
Use Case Name: Manage Shift Preference
Description: This use case outlines the process by which staff can indicate their preferences of their shift timings and locations. The staff can create, update, and delete shift preferences. This would happen every time there is a new scheduling cycle.

Primary Actor: Staff

Preconditions:
Staff must be logged into the system
New scheduling cycle
Staff has preference for shift timings and location

Postconditions: Staff has successfully created, updated, or deleted shift preference as needed.

Main Success Scenarios:

1. User Logs into system
2. System validates login information and determines user roles and displays the corresponding landing page.
3. Staff selects ‘Create Preference’ in the landing page
4. System displays a create preference form
5. Staff fills in new valid preference information into form
6. Staff submits the form
7. System validates input
8. System creates preference for staff
9. System displays successful preference creation.

Alternative Scenarios:
3a. Update Shift Preference:
3a1. Staff selects ‘Update Preference’ on preference selected
3a2. System shows current preference details for editing
3a3. Staff makes modification to the existing location
3a4. Staff clicks on ‘Confirm’ to confirm the update
3a5. System validates input
3a6. System updates the selected preference
3a7. System displays successful preference update.

3b1. Staff selects ‘Delete Preference’ on preference selected
3b2. System shows confirmation popup for deletion
3b3. Staff confirms deletion
3b4. System deletes the selected preference
3b7. System displays successful preference deletion.

7a. Conflicts or errors in the information provided by the Manager (e.g., duplicate shift information), 
7a1. The system displays an error message and prompts the Manager to correct the information.
7a2. Repeat from Step 5
