### ISSUE TITLE
#Task 1.2.4: Performance Requirements

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#18]
**Task 1.2.4**: Performance Requirements

**What is the task about? Please describe in detail.**
The task is about specifying performance requirements for a web-based Workload Management System under various circumstances. Performance requirements are crucial as they define how the system should behave in terms of speed, responsiveness, and capacity. These requirements help developers understand the intent and make appropriate design choices to ensure the system meets its performance objectives. 

**What are the goals of the task? Please describe in detail.**
The goals of this task are to define and explain the rationale behind the specified performance requirements (PR) for the web-based Workload Management System. These performance requirements aim to ensure that the system operates efficiently, responsively, and reliably under various circumstances. 

**Success or completion criteria. Please describe in detail.**
Success: Performance requirements are clearly defined for the system, and corresponding rationales are provided for each requirement.
Completion: The section is considered complete when all relevant performance requirements and their rationales are documented in a clear and concise manner

**Allocated time**
4 days

**Start date and end date of the issue/task**
13/09/2023 - 17/09/2023

**Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.**
Faith

**The status of the task. This is usually "To-Do" initially.**
Completed

**What is the Priority of the task?**
Medium

**Comment by faithlimzx** [comment]
**Describe the work done in detail.**
PR1: Timely Notifications
Work Done: We added a feature that notifies managers when security guards request last-minute leave.
Rationale: This helps managers react quickly to unexpected staffing changes.

PR2: Shift Limit Compliance
Work Done: We built a system that prevents assigning more shifts to security officers than allowed by labor regulations.
Rationale: This ensures security officers' well-being and compliance with labor laws.

PR3: Real-Time Updates
Work Done: We made sure the system updates data within 1 second of user submissions for an efficient and responsive experience.
Rationale: Users get real-time information, enabling quick decisions and data accuracy.

PR4: User Load Handling
Work Done: We ensured the system can handle a minimum number of users simultaneously without slowing down.
Rationale: It guarantees smooth performance even during high usage and prepares for future growth.

PR5: Mobile-Friendly UI
Work Done: We designed the interface to work well on mobile devices, making it easy for users on smartphones and tablets.
Rationale: Mobile access is vital for users who need to manage schedules on the go.

PR6: Scalable Database
Work Done: We created a flexible database structure, allowing easy expansion without rebuilding everything.
Rationale: It ensures the system can grow and adapt smoothly over time.

**Has this work been committed to the repo?**
Yes

**How does the work affect the completion deadline.**
NA

**Are there any changes to the success or completion criteria of the task? If yes, please describe the details.**
NA

**Start date and end date of the work done for this comment.**
13/09/2023 - 17/09/2023

**Comment by faithlimzx** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/78584557/38c8a004-cf8d-4b83-b449-43d51ff5ba36)



![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/78584557/a2c8f02c-6fc2-479f-9757-4147bcb71e96)
