### ISSUE TITLE
#Task 1.4: Software Estimation

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#21]
Task title ID: https://github.com/hxijxe/ict-inf2001-p3-6/issues/17

What is the task about? Please describe in detail.
The process of predicting the time, effort, and resources required to develop the system, considering factors such as the complexity of features, integration with existing systems, and potential risks. It helps project managers and stakeholders assess the project's feasibility, plan resources effectively, and set realistic timelines for its completion.

What are the goals of the task? Please describe in detail.
To provide project stakeholders with a clear understanding of the project's scope and resource requirements, enabling informed decision-making and effective project planning. Additionally, it aims to minimize the risk of budget and timeline overruns by setting realistic expectations and identifying potential challenges early in the development process.

Success or completion criteria. Please describe in detail.
Completion of Use Case Points, and Cocomo

Allocated time
7 Days

Start date and end date of the issue/task
15/09/23 - 21/09/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@avintech

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
Medium

**Comment by avintech** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/64296499/7401ee69-f07b-4a9d-8f63-efe9f81f1a77)

**Comment by avintech** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/64296499/67283d8a-2cc3-4fec-8520-977a0667f019)

**Comment by avintech** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/64296499/5359fc11-96b2-4620-9c47-de73b47b21c3)

**Comment by avintech** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/64296499/b69362b5-6f55-487c-9653-df12fa4eefaa)
