### ISSUE TITLE
#Task 1.1: Project Management

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#22]
**Task title ID: #1.1**

**What is the task about? Please describe in detail.**
The task is about planning the project timeline. To plan the tasks needed and time required to complete the tasks

**What are the goals of the task? Please describe in detail.**
The goal of the task is to ensure the project can be completed on time.

**Success or completion criteria. Please describe in detail.**
1. Gantt chart

**Allocated time**
7 days

**Start date and end date of the issue/task**
Start date: 8 sept 2023
End date: 15 sept 2023

**Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.**
Vivian

**Comment by viviannzh** [comment]
**Describe the work done in detail.**
Gantt Chart and Work breakdown structure completed

**Has this work been committed to the repo?**
NA

**How does the work affect the completion deadline.**
It would affect the submission and project progress.

**Changes to the success or completion criteria of the task**
No changes

**Start date and end date of the work done for this comment.**
Start date: 8 sept 2023
End date: 15 sept 2023
