### ISSUE TITLE
#Task 1.4.2: COCOMO

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#24]
Issue Description: COCOMO Calculation

Task Title ID: #1.4.2

Task Description: Calculate the effort and time of development using basic COCOMO model for our software project.

Task Goals: To estimate the effort and time required for our software project based on COCOMO model

Success and Completion Criteria: Successful calculation of effort in person-months and time of development in months

Allocated Time: 3 days 

Start Date & End Date of the Task: 18/09/2023-21/09/2023

Owner of the Task: Angie 

Status of Task: In-progress

Priority of Task: Medium

**Comment by user963087** [comment]
Work Done Description: Calculated the effort and time of development using the COCOMO model based on the programming languages and parameters we have use for our software (HTML, CSS, SQL, PHP)

Work committed to repo: Not Applicable to this Task

Impact on completion dateline: Completion deadline remains unaffected by COCOMO calculation. This task is primarily for estimation purpose and does not introduce any changes to the project's overall timeline. 

Changes to Success or Completion Criteria of the Task: There are no changes to the success or completion of the task as the calculation remains unchanged. The task is considered completed when our calculations are accurately obtained as per calculated in the report. 

Start Date and End Date of Work Done: 20/09/2023-22/09/2023
