### ISSUE TITLE
#Task 2.2.1: Component Diagram

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#25]
Task title ID:

What is the task about? Please describe in detail.
The task involves crafting a detailed component diagram for the evolving system. The primary objective is to disassemble the system into discernible components, each geared towards a specific functionality. These components are designed to interact with other vital elements on a need-to-know basis, emphasizing the importance of a judiciously structured diagram.

What are the goals of the task? Please describe in detail.

1. Disintegrate the system into discernible components, emphasizing high-level functionality and clear interactions among them.
2. Establish purposeful grouping of components within the diagram to accurately represent their hierarchical relationships and dependencies.

Success or completion criteria. Please describe in detail.

1. The component diagram effectively communicates the relationships and dependencies between components.
2. Components are grouped logically, reflecting a meaningful organization of functionalities.
3. The diagram showcases a hierarchical structure, accurately capturing the levels of functionality within the system.

Allocated time: 1 Week

Start Date: 12/10/2023
End Date: 19/10/2023

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Faith

**Comment by faithlimzx** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/78584557/f31e018a-6a0c-4995-9afd-846053144ddf)
