### ISSUE TITLE
#Task 2.1.1: Entity Class Diagram

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#26]
Task title ID: 2.1.1

What is the task about? Please describe in detail.

The entity class diagram involves identifying, defining, and illustrating entities, attributes, and relationships within our software system. It begins with listing and describing the entities, specifying their attributes, and establishing how they are related to each other. Superclasses and subclasses may also be included to represent inheritance.

What are the goals of the task? Please describe in detail.

The main goals of creating an entity class diagram is to ensure clarity and effective communication among project stakeholders, provide a basis for data modeling, discover and define system requirements, guide the system's design, and offer a documentation resource for the system's architecture. It serves as a visual reference that aids in understanding, designing, and maintaining the system or database.

Allocated time: 3 Days

Start Date: 04/10/2023
End Date: 06/10/2023

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@avintech

**Comment by avintech** [comment]
Describe the work done in detail.
Entity Class Diagram

Identification and listing of the different entities was done. We found different entities such as Certificate, the different Users and Shift. Then, we defined the attributes, and methods for each entity. Then, we establish the relationships between each entity, including cardinality and multiplicity. Lastly, we added in superclasses to represent broader classes.

Has this work been committed to the repo?
Yes

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
Start date: 04/10/23
End date: 06/10/23
