### ISSUE TITLE
#Task 2.6.5: Create Mobile interface

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#29]

**Comment by Kohgi88** [comment]
Task title ID: Task 2.6.5

What is the task about? Please describe in detail.
Creating the wireframes for the "Mobile Interface".

What are the goals of the task? Please describe in detail.
The objective of the assignment is to verify that the wireframes align with the scenarios outlined in the use cases description in M2.

Success or completion criteria. Please describe in detail.
Use case description has to be finalized before commencing the wireframe design process.

Allocated time
6 days

Start date and end date of the issue/task
09/11/23 - 15/11/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@Kohgi88

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
Medium

Describe the work done in detail.
Wireframes developed for the "Mobile Interface". 

![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/113673421/f0b5f6ec-cf0b-4ce4-90cc-876ad000cceb)

Figma Link: https://www.figma.com/file/6Vd2Tfnk99vLO4MXnvvAdC/SE-PROJECT?type=design&node-id=505%3A10&mode=design&t=AcLYabByuIbiNbPJ-1

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
Failure to complete or experiencing delays will result in insufficient time to complete the report documentation and presentation.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
Start date: 09/11/23
End date: 15/11/23
