### ISSUE TITLE
#Task 2.5.1: Describe Design Pattern 1

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#32]
Task title ID:#Task 2.5.1

What is the task about? Please describe in detail.
Design and describe Observer pattern design

What are the goals of the task? Please describe in detail.
Based on the class diagram in M2, find a suitable function to implement the observer pattern

Success or completion criteria. Please describe in detail.
Being able to link the design pattern with the created diagram

Allocated time
2 days

Start date and end date of the issue/task
06/11/23 - 08/11/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@faithlimzx 

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
High

**Comment by user963087** [comment]
Work Done Description:

Work Committed to the Repo:

Impact on Completion Deadline:

Changes to Success or Completion Criteria of Task:

**Comment by faithlimzx** [comment]
The Observer Pattern equips classes with listeners, enabling them to be notified when certain events occur and to respond to the information received. The integration of the observer pattern is particularly instrumental in the functionality of our Notification system. 

When a manager allocates a job to a specific security staff member, the staff member is promptly informed via a tailored notification system. By employing the observer pattern, the notification process will be updated, ensuring that security personnel are reliably informed through the system's infrastructure. Furthermore, the Manager and ITAdministrator classes are designed to subscribe as listeners, allowing them to be alerted in scenarios where a Security Staff member declines an assignment.

Subject (Observable): The “StaffMember” class acts as subjects, maintaining a roster of observers and notifying them when there is a change in shift status or assignment.

Observers: The “ManageShift” control class functions as a concrete observer. This class is notified of relevant events, such as job assignments or rejections, and can take appropriate actions based on these notifications.

Registration Mechanism: The Manager and ITAdministrator classes  can register with the subject class (“StaffMember”) to listen for specific events, such as the rejection or acceptance of a job by Security Staff.

Notification Process: When the state of a shift changes, the subject class iterates through its list of registered observers and invokes their update() method. This allows the observers to execute appropriate actions based on the notification.

Update and Reaction: Upon being notified, the “ManageShift” class will process the update through a method named notify(), which triggers the sendNotification() method to alert the respective security staff member.

By adhering to these principles, the observer pattern within the Notification system promotes a design that is both flexible and maintainable, accommodating changes and expansions with minimal disruption.

**Comment by faithlimzx** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/78584557/a4ae7f7c-4e86-46ff-a40b-216b9bdc9ef5)
