### ISSUE TITLE
#Task 2.5.2: Describe Design Pattern 2

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#33]
Task title ID:#Task 2.5.1

What is the task about? Please describe in detail.
Design and describe Factory pattern design

What are the goals of the task? Please describe in detail.
Based on the class diagram in M2, find a suitable function to implement the factory pattern

Success or completion criteria. Please describe in detail.
Being able to link the design pattern with the created diagram

Allocated time
2 days

Start date and end date of the issue/task
08/11/23 - 10/11/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@faithlimzx 

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
High

**Comment by faithlimzx** [comment]
The application of the Factory Pattern to the "Manage Shift" control class introduces a specialized 'ShiftFactory' class, revolutionizing the way shifts are created and managed within Saturn’s Software Service’s system. This pattern enhances adaptability, ensuring seamless incorporation of new shift types while maintaining a modular and scalable design.

In the core of shift management, the "Manage Shift" control class undergoes an update with the inclusion of the 'ShiftFactory.' The key operations are now orchestrated through dynamic shift creation:

View Shift (viewShift): This function retains its responsibility for retrieving and displaying details of a specific shift identified by its unique ID. The Factory Pattern focuses primarily on the creation aspect, leaving the viewing operation untouched for consistency

Create Shift (createShift): The Factory Pattern takes center stage in shift creation. The control class collaborates with the 'ShiftFactory' to dynamically assess the shift type, invoking the corresponding factory class ('RegularShiftFactory,' 'NightShiftFactory,' etc.). The 'ShiftFactory' then creates an instance of the concrete shift class, ensuring adaptability to changes in shift types and creation logic. 

Separating Regular Shift and Night Shift into separate classes is to manage the distinct properties and attributes that each shift type carries. Segregating the different behaviours and actions of the shift type into separate classes helps to achieve better encapsulation and maintainability as each class becomes responsible for its unique set of behaviours. The separation aligns with the Open/Closed Principle, a SOLID principle, which states that a class should be open for extension but closed for modification. By having separate classes for each shift type, you can extend the system by introducing new classes without modifying the existing ones. This promotes a design that is more resistant to unintended side effects.


![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/78584557/52d34d1a-7c4d-4809-89a6-51a0dfce0654)
