### ISSUE TITLE
#Task 2.6.1: Create IT admin / Manager / Staff  interface

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#34]

**Comment by viviannzh** [comment]
Task title ID: task 2.6.1

What is the task about? Please describe in detail.
creating wireframes for IT admin, manager and staff interfaces. This includes dashboard, manage account (IT admin), manage staff allocation (manager). manage shift preference pages (staff)

What are the goals of the task? Please describe in detail.
The goal of the task is to ensure the wireframes meets the scenarios stated in the use cases description in m2.

Success or completion criteria. Please describe in detail.
the use case description should be finalised before starting to design wireframe.


Allocated time
3 days.

Start date and end date of the issue/task
Start date: 30 oct 2023
End date: 1 nov 2023

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
Vivian

**Comment by viviannzh** [comment]
Describe the work done in detail.
Wireframes for IT admin, manager and staff interface created

Has this work been committed to the repo?
NA

How does the work affect the completion deadline.
If not completed or delayed, there will not be enough time to finish the report documentation and presentation.

Changes to the success or completion criteria of the task
No changes

Start date and end date of the work done for this comment.
Start date: 30 oct 2023
End date: 1 nov 2023
