### ISSUE TITLE
what has been done well

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#36]

**Comment by hxijxe** [comment]
Good teamwork! Everyone worked efficiently together

**Comment by Kohgi88** [comment]
1. Well defined Gantt Chart allowed for timely completion of tasks.
2. Close liaison with client helped to gain a deeper understanding on the success criteria. 
3. Strong cohesion within the team enabled research and ideation processes to flow smoothly.

**Comment by viviannzh** [comment]
1) Smooth collaboration between team members
2) Tasks completed within estimated time allocated

**Comment by user963087** [comment]
1. most of the tasks are completed on time based on project estimation
2. well planned interview with client to focus on the client's needs so that time is not wasted
3. good follow up on every task that we have to complete between team members

**Comment by avintech** [comment]
great teamwork, good collaboration, well described requirements help to make the workload easier to manage and plan

**Comment by faithlimzx** [comment]
Good teamwork and effective communication 
Assigned tasks were completed within the allocated time frame
