### ISSUE TITLE
what can be improved

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#37]

**Comment by hxijxe** [comment]
Better time management.

**Comment by Kohgi88** [comment]
Allocate more time and manpower into domain research to gain clarity on common issues faced by stakeholders.

**Comment by viviannzh** [comment]
Adjust time allocated for tasks as needed to accommodate changes or delays.

**Comment by user963087** [comment]
1. some of the tasks are delayed based on estimation. maybe can improve on time management
2.  can check and remind each other if tasks are not completed on time

**Comment by avintech** [comment]
better time management can help us complete tasks faster

**Comment by faithlimzx** [comment]
Addressing uncertainties could be done earlier to prevent delays 
Having a more structured timeline
