### ISSUE TITLE
#Task 0: Discussion of ideas and preliminary consultation with client

### ISSUE THREAD

**Issue by faithlimzx** [hxijxe/ict-inf2001-p3-6#4]
**Task title ID:** #0

**What is the task about? Please describe in detail.**
Preliminary consultation with client to understand the project

**What are the goals of the task? Please describe in detail.**
1. Understand the requirements of the client and deep dive to get client's needs.
2. Clear out doubts about the the project.
3. Make sure client and us are on the same page.

**Success or completion criteria. Please describe in detail.**
Take down meeting minutes and put at issue comments

**Allocated time**
20mins

**Start date and end date of the issue/task**
05/09/23 11.25am - 11.45am 

**Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.**
@hxijxe 

**The status of the task. This is usually "To-Do" initially.**
Completed

**What is the Priority of the task?**
1. Base on consultation with client, brainstorm functional and non-functional requirements.
2. Define project scope and objectives
3. Identify potential challenges and risks.

**Comment by hxijxe** [comment]
**Describe the work done in detail.**
Meeting Minutes
1. for the shift work don't allow the staff to work overtime want them to finish and hand over asap so will not be confused.
2. shift hours: normally 1 day 2 shifts 12hr 7am - 7pm hand over time self decide.
3. staff with mc: unplanned illness: supply staff with contingency to fill up properly. security outsource, if there's a gap then fill up.
4. ideas to make the workload easier: don't care just give them equal workload. all the security guards must know what they are doing and certificates to prove that they are qualified.
5. when staff missed weekly deadline how dealt: leave to outsource company to manage
6. how to confirm the slot: part timer can say no to some slots but full timer cannot. part timer get one chance to reject 4ever.
7. can notify using in app notification if new assignment/ change\. email better approach.
8. work flow: depends on the location and job, refer to table in the project brief. 
9. challenges: last min decision by part timer they don't want work then have to look for other staff to fill up the role. Full time staff if keep take leave, hard to find people to fill up(can get some part timers to fill up). 
10. at least one person to standby, pay extra if activated.
11. when assigning shift: follow MOM guidelines, cannot back to back shift (8hrs?12hrs?)
12. 7 days work week. each person around 5.5days leave it up to us 
13. plan earlier for some unplanned event: planned ahead, if happen, pay a bit more(lol).
14. terminology look up skill future.
15. Improvise on the go. can assume. need email client to verify/reconfirm.

**Has this work been committed to the repo?**
Yes

**How does the work affect the completion deadline.**
NA

**Are there any changes to the success or completion criteria of the task? If yes, please describe the details.**
NA

**Start date and end date of the work done for this comment.**
Start date: 06/09/23
End date: 06/09/23
