### ISSUE TITLE
#Task 2.3.2: Sequence Diagram 2

### ISSUE THREAD

**Issue by faithlimzx** [hxijxe/ict-inf2001-p3-6#45]
Task title ID: Sequence Diagram 2 (manager)

What is the task about? Please describe in detail.
Create sequence diagram for use case 5, which is one of the ore prominent use case.

What are the goals of the task? Please describe in detail.
Planning of tasks to ensure meeting the submission date.

Success or completion criteria. Please describe in detail.
Class diagram should be completed first before creating sequence diagram as it will be using the same controls, boundary and entity.

Allocated time
4 days

Start date and end date of the issue/task
Start date: 23 oct 2023
End date: 27 oct 2023

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@viviannzh

The status of the task. This is usually "To-Do" initially.
In-progress

What is the Priority of the task?
Medium

**Comment by viviannzh** [comment]
Work done in detail.

1. Based on use case 5, build the sequence diagram
2. Include any alternative senarios as stated in the use case description
3. Make sure to use the same naming convention as what was used in the class diagram

Has this work been committed to the repo?
NA

How does the work affect the completion deadline.

Not completing in time would affect report writing as explaination of the work flow is required.

Changes to the success or completion criteria of the task?
No changes

Start date and end date of the work done for this comment.
Start date: 23 oct 2023
End date: 27 oct 2023
