### ISSUE TITLE
#Task 2.1.2: Boundary Class Diagram

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#47]
Issue Description: To create Boundary Class Diagram

Task Title ID: #2.1.2

Task Description: The task involves creating a Boundary Class Diagram for our security workload management system. 

Task Goals: To create a class diagram to visually represent and illustrate the interactions between the entity and user class. To identify the boundary classes that mediate between the actors and the system. Our boundary class in this case would be the user interface. 

Success and Completion Criteria Description: The boundary class is accurately created and includes all the necessary components. The boundary class diagram correctly shows the connection between the entity and user class.  All relevant boundary classes are identified and properly labelled. 

Allocated Time: 4 days

Start Date & End Date of the Task: 6 Oct 2023 & 9 Oct 2023

Owner of the Tasks: Angie 

Status of the Task: To-Do

Priority of the Task: HIGH priority

**Comment by user963087** [comment]
Work Done Description: The boundary class diagram has been created based on our workload management system design specification. The diagram illustrates the interactions between the entity and user class, highlighting the boundary classes which are the user interface that mediate these interactions. 

Work Committed to Repo: The boundary class diagram has been drawn in our lucid chart diagram. (https://lucid.app/lucidchart/ad464215-83a2-4be9-9e5a-fa84782981c1/edit?viewport_loc=-1051%2C-462%2C3474%2C1554%2C0_0&invitationId=inv_29e81332-2358-4010-a805-d86d139eaad7)

Impact on Completion Dateline: NA 

Changes to Success or Completion Criteria of Task: NA

Start Date & End Date of Work Done: 6 Oct 2023 & 9 Oct 2023 (changes can still be made along the way before we confirm the final class diagram)
