### ISSUE TITLE
#Task 3.1: List flow for prototype / wireframe

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#52]
Task Title ID: #3.1

Task Description: List flow for prototype / wireframe

Task Goals: Create and list the flow for the prototype wireframe for documentation for each use case, their alternative scenarios and error handling

Success and Completion Criteria Description: Successful listing of the flow for our prototype and wireframe for all use case, alternative scenarios and error handling. Ensuring that our wireframe and our flow tally. 

Allocated Time: 7 days

Start Date & End Date of the Task: 15 Nov 2023 - 22 Nov 2023

Owner of the Task: Angie 

Status of the Task: To-Do

Priority of the Task: Low

**Comment by user963087** [comment]
Work Done Description: Successful updated and document the list flow for our wireframe and prototype for our video presentation for all use case, their alternative scenarios and error handling

Work Committed to Repo: NA

Impact on Completion Dateline: NA

Changes to Success or Completion Criteria of Task: NA

Start Date & End Date of Work Done: 17 Nov 2023 - 25 Nov 2023
