### ISSUE TITLE
#Task 3.4: Conduct White-box Testing

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#54]
Task title ID: task 3.4

What is the task about? Please describe in detail.
Conduct White-box Testing

What are the goals of the task? Please describe in detail.
The goal of the task is to conduct White-box testing for usecase 7

Success or completion criteria. Please describe in detail.
calculate and conduct white-box testing

Allocated time
2 days.

Start date and end date of the issue/task
Start date: 21 nov 2023
End date: 23 nov 2023

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@avintech

**Comment by avintech** [comment]
1.Function CreateShiftPreference(preferenceData)
2.            If CheckPreferenceData(preferenceData) Then
3.                    preparedSQL = prepareSQL(‘insert’,’ShiftPreference’,preferenceData)
4.                    insertSuccess = executeSQL(preparedSQL)
5.                    if insertSuccess Then
6.                        result= "Preference successfully created."
7.                    Else
8.                        result= “ShiftPreference failed to insert”
9.                    End If
10.            Else
11.                Display "Invalid preference data"
12.            End If
13.            return result
13.End Function

PseudoCode

**Comment by avintech** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/64296499/10d44a80-fd42-42f9-8430-c8a76963bd6d)

Cyclomatic Complexity:

V(G) = 11 - 10+(2 *1)
V(G) = 11 - 10 +2 
V(G) = 3


With this complexity, we would then have three paths to test:

Path where CheckPreferenceData returns true and executeSQL returns true.
Path where CheckPreferenceData returns true and executeSQL returns false.
Path where CheckPreferenceData returns false.

**Comment by avintech** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-06abe075-7fff-25e0-99be-9fe19ea7272b"><br /><br /><div dir="ltr" style="margin-left:0pt;" align="left">
<table border="1">
  <tr>
    <th>Test Case No.</th>
    <th>CheckPreferenceData</th>
    <th>executeSQL</th>
    <th>Result</th>
  </tr>
  <tr>
    <td>1</td>
    <td>True</td>
    <td>True</td>
    <td>Preference successfully created.</td>
  </tr>
  <tr>
    <td>2</td>
    <td>True</td>
    <td>False</td>
    <td>ShiftPreference failed to insert</td>
  </tr>
  <tr>
    <td>3</td>
    <td>False</td>
    <td>NA</td>
    <td>Invalid preference data.</td>
  </tr>
</table>
</div><br /></b>
</body>
</html>
