### ISSUE TITLE
#Task 3.2 Write description for wireframe

### ISSUE THREAD

**Issue by viviannzh** [hxijxe/ict-inf2001-p3-6#55]
Issue Description: To write description for wireframe for our project

Task Title ID: #3.2 

Task Description: To write description for wireframe for our project in our report. To check whether our wireframe has fulfill for all the requirements and scenarios for our use cases that we stated and mentioned in our M2 and M1.

Task Goals: To document in our report how our wireframe aligns with our use cases and their scenarios

Success and Completion Criteria Description: Successful documented and check that our wireframe aligns with all our use cases and their description

Allocated Time: 7 days

Start Date & End Date of the Task: 15 Nov 2023 - 22 Nov 2023

Owner of the Task: Angie

Status of the Task: To-Do

Priority of the Task: Medium

**Comment by user963087** [comment]
Work Done Description: Documented wireframe description and checked our wireframe aligns with our use cases

Work Committed to Repo: NA 

Impact on Completion Dateline: NA

Changes to Success or Completion Criteria of Task: NA

Start Date & End Date of Work Done: 17 Nov 2023 - 25 Nov 2023
