### ISSUE TITLE
#Task1.1.5: Product Functionality

### ISSUE THREAD

**Issue by faithlimzx** [hxijxe/ict-inf2001-p3-6#7]
Task1: Product Functionality

What is the task about? Please describe in detail.
Providing a concise overview of the primary functions that the product should execute or enable users to perform. This summary should offer a high-level understanding of these functions as outlined in the project description.

What are the goals of the task? Please describe in detail.
To ensure that all stakeholders reading the document would have a clear and shared understanding of the major functions the system has to perform, and also sets the boundaries for what the system is expected to achieve.

Success or completion criteria. Please describe in detail.
NA

Allocated time
7 Days

Start date and end date of the issue/task
29/08/23 - 05/09/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@avintech 

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
Medium

**Comment by avintech** [comment]
Describe the work done in detail.

We have came up with different overall functionality that we felt that our product needs to have, which are the following:
- The product shall allow creating, reading, updating and deleting of job allocation and workload hours
- The product shall allow managers to allocate shifts to security guards based on site and timing
- The product shall allow security guards to indicate interest/preference on shift timings
- The product shall ensure role-based authorisation, allowing managers to access administrative functions and security guards to perform their own tasks.
- The product shall allow managers to view and adjust workload assignments as needed.
- The product shall allow security guards to view their assigned jobs and any relevant details.
- The product shall provide reporting features that allow managers to check the workload distribution among security guards.
- The product should be able to generate reports on guard assignments, hours worked and shift preferences.
- The product shall send notifications to security guards regarding their shift assignments and any changes.
- The product shall send alerts to managers when security guards indicate unavailability or reject job assignments.
- The product shall support availability planning up to several weeks in advance.

Has this work been committed to the repo?
Yes

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
29/08/23 - 05/09/23

**Comment by avintech** [comment]
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/64296499/27ef10f7-3643-44fc-9995-ac372fb5b086)
